plugins=(git colored-man-pages)
eval "$(zoxide init zsh)"

source $ZSH/oh-my-zsh.sh
source $HOME/.aliases.zsh

DISABLE_UNTRACKED_FILES_DIRTY="true"

HISTFILE=~/.cache/zsh/history
HIST_STAMPS="dd/mm/yyyy"

# Color shortcuts
R=$fg_no_bold[red]
B=$fg_no_bold[blue]
M=$fg_no_bold[magenta]
RESET=$reset_color

local return_side="%(?..%{$R%}   %{$RESET%})"

# Prompt
PROMPT='%{$M%}%B%1~%b%{$RESET%} %{$M%}%{$RESET%}'
RPS1="${return_side}"
